// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SensorService.proto

package io.grpc.examples.iotservice;

public interface DadoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sensor_service.Dado)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string data = 2;</code>
   * @return The data.
   */
  java.lang.String getData();
  /**
   * <code>string data = 2;</code>
   * @return The bytes for data.
   */
  com.google.protobuf.ByteString
      getDataBytes();

  /**
   * <code>string localizacao = 3;</code>
   * @return The localizacao.
   */
  java.lang.String getLocalizacao();
  /**
   * <code>string localizacao = 3;</code>
   * @return The bytes for localizacao.
   */
  com.google.protobuf.ByteString
      getLocalizacaoBytes();

  /**
   * <code>string nomeDispositivo = 4;</code>
   * @return The nomeDispositivo.
   */
  java.lang.String getNomeDispositivo();
  /**
   * <code>string nomeDispositivo = 4;</code>
   * @return The bytes for nomeDispositivo.
   */
  com.google.protobuf.ByteString
      getNomeDispositivoBytes();

  /**
   * <code>uint32 tipoDispositivo = 5;</code>
   * @return The tipoDispositivo.
   */
  int getTipoDispositivo();

  /**
   * <code>float valor = 6;</code>
   * @return The valor.
   */
  float getValor();
}
