// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SensorService.proto

package io.grpc.examples.iotservice;

public interface DispositivoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sensor_service.Dispositivo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string nomeDispositivo = 1;</code>
   * @return The nomeDispositivo.
   */
  java.lang.String getNomeDispositivo();
  /**
   * <code>string nomeDispositivo = 1;</code>
   * @return The bytes for nomeDispositivo.
   */
  com.google.protobuf.ByteString
      getNomeDispositivoBytes();

  /**
   * <code>string localizacao = 2;</code>
   * @return The localizacao.
   */
  java.lang.String getLocalizacao();
  /**
   * <code>string localizacao = 2;</code>
   * @return The bytes for localizacao.
   */
  com.google.protobuf.ByteString
      getLocalizacaoBytes();

  /**
   * <code>uint32 tipoDispositivo = 3;</code>
   * @return The tipoDispositivo.
   */
  int getTipoDispositivo();
}
