// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SensorService.proto

package io.grpc.examples.iotservice;

public interface EmptyMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sensor_service.EmptyMessage)
    com.google.protobuf.MessageOrBuilder {
}
