// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SensorService.proto

package io.grpc.examples.iotservice;

public interface LedStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sensor_service.LedStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional uint32 estado = 1;</code>
   * @return Whether the estado field is set.
   */
  boolean hasEstado();
  /**
   * <code>optional uint32 estado = 1;</code>
   * @return The estado.
   */
  int getEstado();

  /**
   * <code>optional string nomeDispositivo = 2;</code>
   * @return Whether the nomeDispositivo field is set.
   */
  boolean hasNomeDispositivo();
  /**
   * <code>optional string nomeDispositivo = 2;</code>
   * @return The nomeDispositivo.
   */
  java.lang.String getNomeDispositivo();
  /**
   * <code>optional string nomeDispositivo = 2;</code>
   * @return The bytes for nomeDispositivo.
   */
  com.google.protobuf.ByteString
      getNomeDispositivoBytes();

  /**
   * <code>string localizacao = 3;</code>
   * @return The localizacao.
   */
  java.lang.String getLocalizacao();
  /**
   * <code>string localizacao = 3;</code>
   * @return The bytes for localizacao.
   */
  com.google.protobuf.ByteString
      getLocalizacaoBytes();
}
