// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SensorService.proto

package io.grpc.examples.iotservice;

public interface ListaLedStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sensor_service.ListaLedStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .sensor_service.LedStatus status = 1;</code>
   */
  java.util.List<io.grpc.examples.iotservice.LedStatus> 
      getStatusList();
  /**
   * <code>repeated .sensor_service.LedStatus status = 1;</code>
   */
  io.grpc.examples.iotservice.LedStatus getStatus(int index);
  /**
   * <code>repeated .sensor_service.LedStatus status = 1;</code>
   */
  int getStatusCount();
  /**
   * <code>repeated .sensor_service.LedStatus status = 1;</code>
   */
  java.util.List<? extends io.grpc.examples.iotservice.LedStatusOrBuilder> 
      getStatusOrBuilderList();
  /**
   * <code>repeated .sensor_service.LedStatus status = 1;</code>
   */
  io.grpc.examples.iotservice.LedStatusOrBuilder getStatusOrBuilder(
      int index);
}
