// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SensorService.proto

package io.grpc.examples.iotservice;

/**
 * Protobuf type {@code sensor_service.ListaDispositivos}
 */
public final class ListaDispositivos extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:sensor_service.ListaDispositivos)
    ListaDispositivosOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ListaDispositivos.newBuilder() to construct.
  private ListaDispositivos(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ListaDispositivos() {
    dispositivos_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ListaDispositivos();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.grpc.examples.iotservice.IoTServiceProto.internal_static_sensor_service_ListaDispositivos_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.grpc.examples.iotservice.IoTServiceProto.internal_static_sensor_service_ListaDispositivos_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.grpc.examples.iotservice.ListaDispositivos.class, io.grpc.examples.iotservice.ListaDispositivos.Builder.class);
  }

  public static final int DISPOSITIVOS_FIELD_NUMBER = 1;
  private java.util.List<io.grpc.examples.iotservice.Dispositivo> dispositivos_;
  /**
   * <code>repeated .sensor_service.Dispositivo dispositivos = 1;</code>
   */
  @java.lang.Override
  public java.util.List<io.grpc.examples.iotservice.Dispositivo> getDispositivosList() {
    return dispositivos_;
  }
  /**
   * <code>repeated .sensor_service.Dispositivo dispositivos = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends io.grpc.examples.iotservice.DispositivoOrBuilder> 
      getDispositivosOrBuilderList() {
    return dispositivos_;
  }
  /**
   * <code>repeated .sensor_service.Dispositivo dispositivos = 1;</code>
   */
  @java.lang.Override
  public int getDispositivosCount() {
    return dispositivos_.size();
  }
  /**
   * <code>repeated .sensor_service.Dispositivo dispositivos = 1;</code>
   */
  @java.lang.Override
  public io.grpc.examples.iotservice.Dispositivo getDispositivos(int index) {
    return dispositivos_.get(index);
  }
  /**
   * <code>repeated .sensor_service.Dispositivo dispositivos = 1;</code>
   */
  @java.lang.Override
  public io.grpc.examples.iotservice.DispositivoOrBuilder getDispositivosOrBuilder(
      int index) {
    return dispositivos_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < dispositivos_.size(); i++) {
      output.writeMessage(1, dispositivos_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < dispositivos_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, dispositivos_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.grpc.examples.iotservice.ListaDispositivos)) {
      return super.equals(obj);
    }
    io.grpc.examples.iotservice.ListaDispositivos other = (io.grpc.examples.iotservice.ListaDispositivos) obj;

    if (!getDispositivosList()
        .equals(other.getDispositivosList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getDispositivosCount() > 0) {
      hash = (37 * hash) + DISPOSITIVOS_FIELD_NUMBER;
      hash = (53 * hash) + getDispositivosList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.grpc.examples.iotservice.ListaDispositivos parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.grpc.examples.iotservice.ListaDispositivos parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.grpc.examples.iotservice.ListaDispositivos parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.grpc.examples.iotservice.ListaDispositivos parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.grpc.examples.iotservice.ListaDispositivos parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.grpc.examples.iotservice.ListaDispositivos parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.grpc.examples.iotservice.ListaDispositivos parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.grpc.examples.iotservice.ListaDispositivos parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.grpc.examples.iotservice.ListaDispositivos parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.grpc.examples.iotservice.ListaDispositivos parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.grpc.examples.iotservice.ListaDispositivos parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.grpc.examples.iotservice.ListaDispositivos parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.grpc.examples.iotservice.ListaDispositivos prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code sensor_service.ListaDispositivos}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:sensor_service.ListaDispositivos)
      io.grpc.examples.iotservice.ListaDispositivosOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.grpc.examples.iotservice.IoTServiceProto.internal_static_sensor_service_ListaDispositivos_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.grpc.examples.iotservice.IoTServiceProto.internal_static_sensor_service_ListaDispositivos_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.grpc.examples.iotservice.ListaDispositivos.class, io.grpc.examples.iotservice.ListaDispositivos.Builder.class);
    }

    // Construct using io.grpc.examples.iotservice.ListaDispositivos.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (dispositivosBuilder_ == null) {
        dispositivos_ = java.util.Collections.emptyList();
      } else {
        dispositivos_ = null;
        dispositivosBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.grpc.examples.iotservice.IoTServiceProto.internal_static_sensor_service_ListaDispositivos_descriptor;
    }

    @java.lang.Override
    public io.grpc.examples.iotservice.ListaDispositivos getDefaultInstanceForType() {
      return io.grpc.examples.iotservice.ListaDispositivos.getDefaultInstance();
    }

    @java.lang.Override
    public io.grpc.examples.iotservice.ListaDispositivos build() {
      io.grpc.examples.iotservice.ListaDispositivos result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.grpc.examples.iotservice.ListaDispositivos buildPartial() {
      io.grpc.examples.iotservice.ListaDispositivos result = new io.grpc.examples.iotservice.ListaDispositivos(this);
      int from_bitField0_ = bitField0_;
      if (dispositivosBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          dispositivos_ = java.util.Collections.unmodifiableList(dispositivos_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.dispositivos_ = dispositivos_;
      } else {
        result.dispositivos_ = dispositivosBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.grpc.examples.iotservice.ListaDispositivos) {
        return mergeFrom((io.grpc.examples.iotservice.ListaDispositivos)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.grpc.examples.iotservice.ListaDispositivos other) {
      if (other == io.grpc.examples.iotservice.ListaDispositivos.getDefaultInstance()) return this;
      if (dispositivosBuilder_ == null) {
        if (!other.dispositivos_.isEmpty()) {
          if (dispositivos_.isEmpty()) {
            dispositivos_ = other.dispositivos_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureDispositivosIsMutable();
            dispositivos_.addAll(other.dispositivos_);
          }
          onChanged();
        }
      } else {
        if (!other.dispositivos_.isEmpty()) {
          if (dispositivosBuilder_.isEmpty()) {
            dispositivosBuilder_.dispose();
            dispositivosBuilder_ = null;
            dispositivos_ = other.dispositivos_;
            bitField0_ = (bitField0_ & ~0x00000001);
            dispositivosBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getDispositivosFieldBuilder() : null;
          } else {
            dispositivosBuilder_.addAllMessages(other.dispositivos_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              io.grpc.examples.iotservice.Dispositivo m =
                  input.readMessage(
                      io.grpc.examples.iotservice.Dispositivo.parser(),
                      extensionRegistry);
              if (dispositivosBuilder_ == null) {
                ensureDispositivosIsMutable();
                dispositivos_.add(m);
              } else {
                dispositivosBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<io.grpc.examples.iotservice.Dispositivo> dispositivos_ =
      java.util.Collections.emptyList();
    private void ensureDispositivosIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        dispositivos_ = new java.util.ArrayList<io.grpc.examples.iotservice.Dispositivo>(dispositivos_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.grpc.examples.iotservice.Dispositivo, io.grpc.examples.iotservice.Dispositivo.Builder, io.grpc.examples.iotservice.DispositivoOrBuilder> dispositivosBuilder_;

    /**
     * <code>repeated .sensor_service.Dispositivo dispositivos = 1;</code>
     */
    public java.util.List<io.grpc.examples.iotservice.Dispositivo> getDispositivosList() {
      if (dispositivosBuilder_ == null) {
        return java.util.Collections.unmodifiableList(dispositivos_);
      } else {
        return dispositivosBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .sensor_service.Dispositivo dispositivos = 1;</code>
     */
    public int getDispositivosCount() {
      if (dispositivosBuilder_ == null) {
        return dispositivos_.size();
      } else {
        return dispositivosBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .sensor_service.Dispositivo dispositivos = 1;</code>
     */
    public io.grpc.examples.iotservice.Dispositivo getDispositivos(int index) {
      if (dispositivosBuilder_ == null) {
        return dispositivos_.get(index);
      } else {
        return dispositivosBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .sensor_service.Dispositivo dispositivos = 1;</code>
     */
    public Builder setDispositivos(
        int index, io.grpc.examples.iotservice.Dispositivo value) {
      if (dispositivosBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDispositivosIsMutable();
        dispositivos_.set(index, value);
        onChanged();
      } else {
        dispositivosBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .sensor_service.Dispositivo dispositivos = 1;</code>
     */
    public Builder setDispositivos(
        int index, io.grpc.examples.iotservice.Dispositivo.Builder builderForValue) {
      if (dispositivosBuilder_ == null) {
        ensureDispositivosIsMutable();
        dispositivos_.set(index, builderForValue.build());
        onChanged();
      } else {
        dispositivosBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .sensor_service.Dispositivo dispositivos = 1;</code>
     */
    public Builder addDispositivos(io.grpc.examples.iotservice.Dispositivo value) {
      if (dispositivosBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDispositivosIsMutable();
        dispositivos_.add(value);
        onChanged();
      } else {
        dispositivosBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .sensor_service.Dispositivo dispositivos = 1;</code>
     */
    public Builder addDispositivos(
        int index, io.grpc.examples.iotservice.Dispositivo value) {
      if (dispositivosBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDispositivosIsMutable();
        dispositivos_.add(index, value);
        onChanged();
      } else {
        dispositivosBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .sensor_service.Dispositivo dispositivos = 1;</code>
     */
    public Builder addDispositivos(
        io.grpc.examples.iotservice.Dispositivo.Builder builderForValue) {
      if (dispositivosBuilder_ == null) {
        ensureDispositivosIsMutable();
        dispositivos_.add(builderForValue.build());
        onChanged();
      } else {
        dispositivosBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .sensor_service.Dispositivo dispositivos = 1;</code>
     */
    public Builder addDispositivos(
        int index, io.grpc.examples.iotservice.Dispositivo.Builder builderForValue) {
      if (dispositivosBuilder_ == null) {
        ensureDispositivosIsMutable();
        dispositivos_.add(index, builderForValue.build());
        onChanged();
      } else {
        dispositivosBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .sensor_service.Dispositivo dispositivos = 1;</code>
     */
    public Builder addAllDispositivos(
        java.lang.Iterable<? extends io.grpc.examples.iotservice.Dispositivo> values) {
      if (dispositivosBuilder_ == null) {
        ensureDispositivosIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, dispositivos_);
        onChanged();
      } else {
        dispositivosBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .sensor_service.Dispositivo dispositivos = 1;</code>
     */
    public Builder clearDispositivos() {
      if (dispositivosBuilder_ == null) {
        dispositivos_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        dispositivosBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .sensor_service.Dispositivo dispositivos = 1;</code>
     */
    public Builder removeDispositivos(int index) {
      if (dispositivosBuilder_ == null) {
        ensureDispositivosIsMutable();
        dispositivos_.remove(index);
        onChanged();
      } else {
        dispositivosBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .sensor_service.Dispositivo dispositivos = 1;</code>
     */
    public io.grpc.examples.iotservice.Dispositivo.Builder getDispositivosBuilder(
        int index) {
      return getDispositivosFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .sensor_service.Dispositivo dispositivos = 1;</code>
     */
    public io.grpc.examples.iotservice.DispositivoOrBuilder getDispositivosOrBuilder(
        int index) {
      if (dispositivosBuilder_ == null) {
        return dispositivos_.get(index);  } else {
        return dispositivosBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .sensor_service.Dispositivo dispositivos = 1;</code>
     */
    public java.util.List<? extends io.grpc.examples.iotservice.DispositivoOrBuilder> 
         getDispositivosOrBuilderList() {
      if (dispositivosBuilder_ != null) {
        return dispositivosBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(dispositivos_);
      }
    }
    /**
     * <code>repeated .sensor_service.Dispositivo dispositivos = 1;</code>
     */
    public io.grpc.examples.iotservice.Dispositivo.Builder addDispositivosBuilder() {
      return getDispositivosFieldBuilder().addBuilder(
          io.grpc.examples.iotservice.Dispositivo.getDefaultInstance());
    }
    /**
     * <code>repeated .sensor_service.Dispositivo dispositivos = 1;</code>
     */
    public io.grpc.examples.iotservice.Dispositivo.Builder addDispositivosBuilder(
        int index) {
      return getDispositivosFieldBuilder().addBuilder(
          index, io.grpc.examples.iotservice.Dispositivo.getDefaultInstance());
    }
    /**
     * <code>repeated .sensor_service.Dispositivo dispositivos = 1;</code>
     */
    public java.util.List<io.grpc.examples.iotservice.Dispositivo.Builder> 
         getDispositivosBuilderList() {
      return getDispositivosFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.grpc.examples.iotservice.Dispositivo, io.grpc.examples.iotservice.Dispositivo.Builder, io.grpc.examples.iotservice.DispositivoOrBuilder> 
        getDispositivosFieldBuilder() {
      if (dispositivosBuilder_ == null) {
        dispositivosBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            io.grpc.examples.iotservice.Dispositivo, io.grpc.examples.iotservice.Dispositivo.Builder, io.grpc.examples.iotservice.DispositivoOrBuilder>(
                dispositivos_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        dispositivos_ = null;
      }
      return dispositivosBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:sensor_service.ListaDispositivos)
  }

  // @@protoc_insertion_point(class_scope:sensor_service.ListaDispositivos)
  private static final io.grpc.examples.iotservice.ListaDispositivos DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.grpc.examples.iotservice.ListaDispositivos();
  }

  public static io.grpc.examples.iotservice.ListaDispositivos getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ListaDispositivos>
      PARSER = new com.google.protobuf.AbstractParser<ListaDispositivos>() {
    @java.lang.Override
    public ListaDispositivos parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ListaDispositivos> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ListaDispositivos> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.grpc.examples.iotservice.ListaDispositivos getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

