// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SensorService.proto

package io.grpc.examples.iotservice;

public interface ParametrosOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sensor_service.Parametros)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string localizacao = 1;</code>
   * @return The localizacao.
   */
  java.lang.String getLocalizacao();
  /**
   * <code>string localizacao = 1;</code>
   * @return The bytes for localizacao.
   */
  com.google.protobuf.ByteString
      getLocalizacaoBytes();

  /**
   * <code>optional string data = 2;</code>
   * @return Whether the data field is set.
   */
  boolean hasData();
  /**
   * <code>optional string data = 2;</code>
   * @return The data.
   */
  java.lang.String getData();
  /**
   * <code>optional string data = 2;</code>
   * @return The bytes for data.
   */
  com.google.protobuf.ByteString
      getDataBytes();

  /**
   * <code>optional string nomeDispositivo = 3;</code>
   * @return Whether the nomeDispositivo field is set.
   */
  boolean hasNomeDispositivo();
  /**
   * <code>optional string nomeDispositivo = 3;</code>
   * @return The nomeDispositivo.
   */
  java.lang.String getNomeDispositivo();
  /**
   * <code>optional string nomeDispositivo = 3;</code>
   * @return The bytes for nomeDispositivo.
   */
  com.google.protobuf.ByteString
      getNomeDispositivoBytes();
}
