// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SensorService.proto

package io.grpc.examples.iotservice;

public interface ParamLoginOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sensor_service.ParamLogin)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string usuario = 1;</code>
   * @return The usuario.
   */
  java.lang.String getUsuario();
  /**
   * <code>string usuario = 1;</code>
   * @return The bytes for usuario.
   */
  com.google.protobuf.ByteString
      getUsuarioBytes();

  /**
   * <code>string senha = 2;</code>
   * @return The senha.
   */
  java.lang.String getSenha();
  /**
   * <code>string senha = 2;</code>
   * @return The bytes for senha.
   */
  com.google.protobuf.ByteString
      getSenhaBytes();
}
