// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SensorService.proto

package io.grpc.examples.iotservice;

/**
 * Protobuf type {@code sensor_service.Parametros}
 */
public final class Parametros extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:sensor_service.Parametros)
    ParametrosOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Parametros.newBuilder() to construct.
  private Parametros(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Parametros() {
    localizacao_ = "";
    data_ = "";
    nomeDispositivo_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Parametros();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.grpc.examples.iotservice.IoTServiceProto.internal_static_sensor_service_Parametros_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.grpc.examples.iotservice.IoTServiceProto.internal_static_sensor_service_Parametros_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.grpc.examples.iotservice.Parametros.class, io.grpc.examples.iotservice.Parametros.Builder.class);
  }

  private int bitField0_;
  public static final int LOCALIZACAO_FIELD_NUMBER = 1;
  private volatile java.lang.Object localizacao_;
  /**
   * <code>string localizacao = 1;</code>
   * @return The localizacao.
   */
  @java.lang.Override
  public java.lang.String getLocalizacao() {
    java.lang.Object ref = localizacao_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      localizacao_ = s;
      return s;
    }
  }
  /**
   * <code>string localizacao = 1;</code>
   * @return The bytes for localizacao.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLocalizacaoBytes() {
    java.lang.Object ref = localizacao_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      localizacao_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DATA_FIELD_NUMBER = 2;
  private volatile java.lang.Object data_;
  /**
   * <code>optional string data = 2;</code>
   * @return Whether the data field is set.
   */
  @java.lang.Override
  public boolean hasData() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional string data = 2;</code>
   * @return The data.
   */
  @java.lang.Override
  public java.lang.String getData() {
    java.lang.Object ref = data_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      data_ = s;
      return s;
    }
  }
  /**
   * <code>optional string data = 2;</code>
   * @return The bytes for data.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDataBytes() {
    java.lang.Object ref = data_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      data_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NOMEDISPOSITIVO_FIELD_NUMBER = 3;
  private volatile java.lang.Object nomeDispositivo_;
  /**
   * <code>optional string nomeDispositivo = 3;</code>
   * @return Whether the nomeDispositivo field is set.
   */
  @java.lang.Override
  public boolean hasNomeDispositivo() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional string nomeDispositivo = 3;</code>
   * @return The nomeDispositivo.
   */
  @java.lang.Override
  public java.lang.String getNomeDispositivo() {
    java.lang.Object ref = nomeDispositivo_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      nomeDispositivo_ = s;
      return s;
    }
  }
  /**
   * <code>optional string nomeDispositivo = 3;</code>
   * @return The bytes for nomeDispositivo.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNomeDispositivoBytes() {
    java.lang.Object ref = nomeDispositivo_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      nomeDispositivo_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(localizacao_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, localizacao_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, data_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, nomeDispositivo_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(localizacao_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, localizacao_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, data_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, nomeDispositivo_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.grpc.examples.iotservice.Parametros)) {
      return super.equals(obj);
    }
    io.grpc.examples.iotservice.Parametros other = (io.grpc.examples.iotservice.Parametros) obj;

    if (!getLocalizacao()
        .equals(other.getLocalizacao())) return false;
    if (hasData() != other.hasData()) return false;
    if (hasData()) {
      if (!getData()
          .equals(other.getData())) return false;
    }
    if (hasNomeDispositivo() != other.hasNomeDispositivo()) return false;
    if (hasNomeDispositivo()) {
      if (!getNomeDispositivo()
          .equals(other.getNomeDispositivo())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + LOCALIZACAO_FIELD_NUMBER;
    hash = (53 * hash) + getLocalizacao().hashCode();
    if (hasData()) {
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
    }
    if (hasNomeDispositivo()) {
      hash = (37 * hash) + NOMEDISPOSITIVO_FIELD_NUMBER;
      hash = (53 * hash) + getNomeDispositivo().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.grpc.examples.iotservice.Parametros parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.grpc.examples.iotservice.Parametros parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.grpc.examples.iotservice.Parametros parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.grpc.examples.iotservice.Parametros parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.grpc.examples.iotservice.Parametros parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.grpc.examples.iotservice.Parametros parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.grpc.examples.iotservice.Parametros parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.grpc.examples.iotservice.Parametros parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.grpc.examples.iotservice.Parametros parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.grpc.examples.iotservice.Parametros parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.grpc.examples.iotservice.Parametros parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.grpc.examples.iotservice.Parametros parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.grpc.examples.iotservice.Parametros prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code sensor_service.Parametros}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:sensor_service.Parametros)
      io.grpc.examples.iotservice.ParametrosOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.grpc.examples.iotservice.IoTServiceProto.internal_static_sensor_service_Parametros_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.grpc.examples.iotservice.IoTServiceProto.internal_static_sensor_service_Parametros_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.grpc.examples.iotservice.Parametros.class, io.grpc.examples.iotservice.Parametros.Builder.class);
    }

    // Construct using io.grpc.examples.iotservice.Parametros.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      localizacao_ = "";

      data_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      nomeDispositivo_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.grpc.examples.iotservice.IoTServiceProto.internal_static_sensor_service_Parametros_descriptor;
    }

    @java.lang.Override
    public io.grpc.examples.iotservice.Parametros getDefaultInstanceForType() {
      return io.grpc.examples.iotservice.Parametros.getDefaultInstance();
    }

    @java.lang.Override
    public io.grpc.examples.iotservice.Parametros build() {
      io.grpc.examples.iotservice.Parametros result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.grpc.examples.iotservice.Parametros buildPartial() {
      io.grpc.examples.iotservice.Parametros result = new io.grpc.examples.iotservice.Parametros(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.localizacao_ = localizacao_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        to_bitField0_ |= 0x00000001;
      }
      result.data_ = data_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        to_bitField0_ |= 0x00000002;
      }
      result.nomeDispositivo_ = nomeDispositivo_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.grpc.examples.iotservice.Parametros) {
        return mergeFrom((io.grpc.examples.iotservice.Parametros)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.grpc.examples.iotservice.Parametros other) {
      if (other == io.grpc.examples.iotservice.Parametros.getDefaultInstance()) return this;
      if (!other.getLocalizacao().isEmpty()) {
        localizacao_ = other.localizacao_;
        onChanged();
      }
      if (other.hasData()) {
        bitField0_ |= 0x00000001;
        data_ = other.data_;
        onChanged();
      }
      if (other.hasNomeDispositivo()) {
        bitField0_ |= 0x00000002;
        nomeDispositivo_ = other.nomeDispositivo_;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              localizacao_ = input.readStringRequireUtf8();

              break;
            } // case 10
            case 18: {
              data_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 18
            case 26: {
              nomeDispositivo_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object localizacao_ = "";
    /**
     * <code>string localizacao = 1;</code>
     * @return The localizacao.
     */
    public java.lang.String getLocalizacao() {
      java.lang.Object ref = localizacao_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        localizacao_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string localizacao = 1;</code>
     * @return The bytes for localizacao.
     */
    public com.google.protobuf.ByteString
        getLocalizacaoBytes() {
      java.lang.Object ref = localizacao_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        localizacao_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string localizacao = 1;</code>
     * @param value The localizacao to set.
     * @return This builder for chaining.
     */
    public Builder setLocalizacao(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      localizacao_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string localizacao = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearLocalizacao() {
      
      localizacao_ = getDefaultInstance().getLocalizacao();
      onChanged();
      return this;
    }
    /**
     * <code>string localizacao = 1;</code>
     * @param value The bytes for localizacao to set.
     * @return This builder for chaining.
     */
    public Builder setLocalizacaoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      localizacao_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object data_ = "";
    /**
     * <code>optional string data = 2;</code>
     * @return Whether the data field is set.
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string data = 2;</code>
     * @return The data.
     */
    public java.lang.String getData() {
      java.lang.Object ref = data_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        data_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string data = 2;</code>
     * @return The bytes for data.
     */
    public com.google.protobuf.ByteString
        getDataBytes() {
      java.lang.Object ref = data_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        data_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string data = 2;</code>
     * @param value The data to set.
     * @return This builder for chaining.
     */
    public Builder setData(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      data_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string data = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearData() {
      bitField0_ = (bitField0_ & ~0x00000001);
      data_ = getDefaultInstance().getData();
      onChanged();
      return this;
    }
    /**
     * <code>optional string data = 2;</code>
     * @param value The bytes for data to set.
     * @return This builder for chaining.
     */
    public Builder setDataBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000001;
      data_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object nomeDispositivo_ = "";
    /**
     * <code>optional string nomeDispositivo = 3;</code>
     * @return Whether the nomeDispositivo field is set.
     */
    public boolean hasNomeDispositivo() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string nomeDispositivo = 3;</code>
     * @return The nomeDispositivo.
     */
    public java.lang.String getNomeDispositivo() {
      java.lang.Object ref = nomeDispositivo_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nomeDispositivo_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string nomeDispositivo = 3;</code>
     * @return The bytes for nomeDispositivo.
     */
    public com.google.protobuf.ByteString
        getNomeDispositivoBytes() {
      java.lang.Object ref = nomeDispositivo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nomeDispositivo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string nomeDispositivo = 3;</code>
     * @param value The nomeDispositivo to set.
     * @return This builder for chaining.
     */
    public Builder setNomeDispositivo(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      nomeDispositivo_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string nomeDispositivo = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearNomeDispositivo() {
      bitField0_ = (bitField0_ & ~0x00000002);
      nomeDispositivo_ = getDefaultInstance().getNomeDispositivo();
      onChanged();
      return this;
    }
    /**
     * <code>optional string nomeDispositivo = 3;</code>
     * @param value The bytes for nomeDispositivo to set.
     * @return This builder for chaining.
     */
    public Builder setNomeDispositivoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000002;
      nomeDispositivo_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:sensor_service.Parametros)
  }

  // @@protoc_insertion_point(class_scope:sensor_service.Parametros)
  private static final io.grpc.examples.iotservice.Parametros DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.grpc.examples.iotservice.Parametros();
  }

  public static io.grpc.examples.iotservice.Parametros getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Parametros>
      PARSER = new com.google.protobuf.AbstractParser<Parametros>() {
    @java.lang.Override
    public Parametros parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Parametros> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Parametros> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.grpc.examples.iotservice.Parametros getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

