// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SensorService.proto

package io.grpc.examples.iotservice;

public interface SessaoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sensor_service.Sessao)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string token = 1;</code>
   * @return The token.
   */
  java.lang.String getToken();
  /**
   * <code>string token = 1;</code>
   * @return The bytes for token.
   */
  com.google.protobuf.ByteString
      getTokenBytes();

  /**
   * <code>optional string funcionalidade = 2;</code>
   * @return Whether the funcionalidade field is set.
   */
  boolean hasFuncionalidade();
  /**
   * <code>optional string funcionalidade = 2;</code>
   * @return The funcionalidade.
   */
  java.lang.String getFuncionalidade();
  /**
   * <code>optional string funcionalidade = 2;</code>
   * @return The bytes for funcionalidade.
   */
  com.google.protobuf.ByteString
      getFuncionalidadeBytes();
}
